### ISSUE TITLE
Progress tracker

### ISSUE THREAD

**Issue by Perksey** [Ultz/SuperTools#1]
# 1.0
## SuperInvoke
- [x] Boolean Marshalling
- [x] Delegates (with lifetime)
- [x] Pinnable reference marshalling (see also: SpanOverloader in Silk.NET)
- [x] String marshalling (StringOverloader & StringReturnOverloader in Silk.NET)
- [x] By-ref marshalling (FlowPointerOverloader in Silk.NET)
- [x] Multi-parameter pointers (StaticCountOverloader in Silk.NET)
- [ ] String collection marshalling

## SuperPack
- Scrapped
 
## SuperBind
- Scrapped

# Future
## Project Nathaniel
